/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cadence)
#  Generated on:      Wed Jun 24 13:35:00 2026
#  Design:            TrafficLight
#  Command:           saveNetlist physical_netlist_TrafficLight.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jun  9 2026 15:25:50 IST (Jun  9 2026 09:55:50 UTC)
// Verification Directory fv/TrafficLight 
module TrafficLight (
	clk, 
	rst, 
	LED_NS, 
	LED_WE);
   input clk;
   input rst;
   output [2:0] LED_NS;
   output [2:0] LED_WE;

   // Internal wires
   wire FE_OCPN16_n_172;
   wire FE_OCPN15_n_419;
   wire FE_OCPN14_n_28;
   wire FE_OCPN13_FE_DBTN1_state_3;
   wire FE_OCPN12_n_15;
   wire FE_OCPN11_n_71;
   wire FE_OCPN10_n_419;
   wire FE_OCPN9_n_194;
   wire FE_OCPN7_n_419;
   wire FE_OCPN6_n_393;
   wire FE_RN_1_0;
   wire FE_RN_0_0;
   wire FE_RN_1;
   wire FE_OCPN5_n_402;
   wire FE_OCPN4_n_259;
   wire FE_OCPN2_n_422;
   wire FE_DBTN2_state_5;
   wire FE_DBTN1_state_3;
   wire FE_DBTN0_state_1;
   wire [3:0] count;
   wire [5:0] state;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire n_7;
   wire n_14;
   wire n_15;
   wire n_28;
   wire n_37;
   wire n_43;
   wire n_45;
   wire n_56;
   wire n_60;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_79;
   wire n_84;
   wire n_87;
   wire n_88;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_95;
   wire n_96;
   wire n_101;
   wire n_119;
   wire n_172;
   wire n_180;
   wire n_181;
   wire n_187;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_197;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_209;
   wire n_212;
   wire n_215;
   wire n_221;
   wire n_222;
   wire n_223;
   wire n_224;
   wire n_225;
   wire n_229;
   wire n_259;
   wire n_262;
   wire n_267;
   wire n_269;
   wire n_270;
   wire n_289;
   wire n_304;
   wire n_317;
   wire n_318;
   wire n_348;
   wire n_354;
   wire n_355;
   wire n_364;
   wire n_365;
   wire n_366;
   wire n_368;
   wire n_369;
   wire n_373;
   wire n_393;
   wire n_394;
   wire n_396;
   wire n_397;
   wire n_399;
   wire n_400;
   wire n_401;
   wire n_402;
   wire n_404;
   wire n_405;
   wire n_406;
   wire n_408;
   wire n_409;
   wire n_419;
   wire n_420;
   wire n_421;
   wire n_422;
   wire n_423;
   wire n_426;
   wire n_428;
   wire n_429;
   wire n_442;

   CLKBUFX2 FE_OCPC16_n_172 (.A(n_172),
	.Y(FE_OCPN16_n_172));
   CLKBUFX2 FE_OCPC15_n_419 (.A(n_419),
	.Y(FE_OCPN15_n_419));
   CLKBUFX2 FE_OCPC14_n_28 (.A(n_28),
	.Y(FE_OCPN14_n_28));
   AOI22X2 FE_RC_22_0 (.A0(n_72),
	.A1(n_74),
	.B0(n_212),
	.B1(n_71),
	.Y(n_73));
   CLKBUFX2 FE_OCPC13_FE_DBTN1_state_3 (.A(FE_DBTN1_state_3),
	.Y(FE_OCPN13_FE_DBTN1_state_3));
   CLKBUFX2 FE_OCPC12_n_15 (.A(n_15),
	.Y(FE_OCPN12_n_15));
   CLKBUFX2 FE_OCPC11_n_71 (.A(n_71),
	.Y(FE_OCPN11_n_71));
   AOI22X1 FE_RC_21_0 (.A0(n_79),
	.A1(n_72),
	.B0(n_74),
	.B1(FE_OCPN10_n_419),
	.Y(n_355));
   CLKBUFX2 FE_OCPC10_n_419 (.A(n_419),
	.Y(FE_OCPN10_n_419));
   NAND3X2 FE_RC_20_0 (.A(FE_RN_1),
	.B(n_180),
	.C(n_406),
	.Y(n_259));
   NAND3X4 FE_RC_19_0 (.A(n_37),
	.B(n_14),
	.C(n_408),
	.Y(n_409));
   AOI21X4 FE_RC_18_0 (.A0(n_79),
	.A1(n_399),
	.B0(n_262),
	.Y(n_400));
   CLKBUFX2 FE_OCPC9_n_194 (.A(n_194),
	.Y(FE_OCPN9_n_194));
   CLKBUFX2 FE_OCPC7_n_419 (.A(n_419),
	.Y(FE_OCPN7_n_419));
   CLKBUFX2 FE_OCPC6_n_393 (.A(n_393),
	.Y(FE_OCPN6_n_393));
   INVX6 FE_RC_8_0 (.A(state[1]),
	.Y(FE_DBTN0_state_1));
   CLKINVX1 FE_RC_6_0 (.A(count[2]),
	.Y(FE_RN_1_0));
   OAI22X1 FE_RC_5_0 (.A0(FE_RN_1_0),
	.A1(n_422),
	.B0(n_215),
	.B1(n_224),
	.Y(n_225));
   CLKINVX1 FE_RC_4_0 (.A(count[3]),
	.Y(FE_RN_0_0));
   OAI22X1 FE_RC_3_0 (.A0(n_422),
	.A1(FE_RN_0_0),
	.B0(n_215),
	.B1(n_95),
	.Y(n_267));
   NOR2X4 g10834__10889_dup (.A(state[4]),
	.B(state[2]),
	.Y(FE_RN_1));
   CLKINVX4 FE_RC_2_0 (.A(state[0]),
	.Y(n_402));
   AOI21X4 FE_RC_1_0 (.A0(n_229),
	.A1(FE_OCPN4_n_259),
	.B0(n_207),
	.Y(n_262));
   CLKBUFX2 FE_OCPC5_n_402 (.A(n_402),
	.Y(FE_OCPN5_n_402));
   NAND3X2 FE_RC_0_0 (.A(n_37),
	.B(n_119),
	.C(n_396),
	.Y(n_397));
   BUFX3 FE_OCPC4_n_259 (.A(n_259),
	.Y(FE_OCPN4_n_259));
   CLKINVX1 FE_OCPC4_n_422 (.A(n_422),
	.Y(FE_OCPN2_n_422));
   INVXL FE_OCPC1_n_422 (.A(n_422),
	.Y(n_96));
   CLKINVX6 FE_DBTC2_state_5 (.A(state[5]),
	.Y(FE_DBTN2_state_5));
   CLKINVX6 FE_DBTC1_state_3 (.A(state[3]),
	.Y(FE_DBTN1_state_3));
   DFFRHQX4 \count_reg[2]  (.CK(clk),
	.D(n_225),
	.Q(count[2]),
	.RN(n_101));
   DFFRHQX2 \count_reg[3]  (.CK(clk),
	.D(n_267),
	.Q(count[3]),
	.RN(n_101));
   DFFRX2 \count_reg[1]  (.CK(clk),
	.D(n_401),
	.Q(n_304),
	.QN(count[1]),
	.RN(n_101));
   SDFFRHQX2 \count_reg[0]  (.CK(clk),
	.D(FE_OCPN2_n_422),
	.Q(count[0]),
	.RN(n_101),
	.SE(n_317),
	.SI(n_84));
   DFFRHQX4 \state_reg[3]  (.CK(clk),
	.D(n_87),
	.Q(state[3]),
	.RN(n_101));
   DFFRHQX4 \state_reg[5]  (.CK(clk),
	.D(n_88),
	.Q(state[5]),
	.RN(n_101));
   DFFRHQX4 \state_reg[4]  (.CK(clk),
	.D(n_90),
	.Q(state[4]),
	.RN(n_101));
   DFFRHQX4 \state_reg[2]  (.CK(clk),
	.D(n_92),
	.Q(state[2]),
	.RN(n_101));
   DFFRHQX4 \state_reg[1]  (.CK(clk),
	.D(n_91),
	.Q(state[1]),
	.RN(n_101));
   TLATNXL \LED_NS_reg[0]  (.D(FE_OCPN11_n_71),
	.GN(n_96),
	.Q(LED_NS[0]),
	.QN(UNCONNECTED));
   AOI21X2 g10757__4319 (.A0(n_422),
	.A1(n_56),
	.B0(n_369),
	.Y(n_95));
   OAI21X1 g10759__5526 (.A0(n_422),
	.A1(FE_OCPN12_n_15),
	.B0(n_428),
	.Y(n_92));
   OAI21X1 g10756__6783 (.A0(n_422),
	.A1(FE_DBTN0_state_1),
	.B0(n_209),
	.Y(n_91));
   TLATNXL \LED_NS_reg[1]  (.D(FE_OCPN9_n_194),
	.GN(n_96),
	.Q(LED_NS[1]),
	.QN(UNCONNECTED0));
   TLATNXL \LED_WE_reg[2]  (.D(n_354),
	.GN(n_96),
	.Q(LED_WE[2]),
	.QN(UNCONNECTED1));
   TLATNXL \LED_NS_reg[2]  (.D(n_197),
	.GN(n_96),
	.Q(LED_NS[2]),
	.QN(UNCONNECTED2));
   OAI21X1 g10762__3680 (.A0(n_422),
	.A1(FE_OCPN14_n_28),
	.B0(n_426),
	.Y(n_90));
   TLATNXL \LED_WE_reg[1]  (.D(FE_OCPN7_n_419),
	.GN(n_96),
	.Q(LED_WE[1]),
	.QN(UNCONNECTED3));
   OAI21X1 g10761__2802 (.A0(n_422),
	.A1(FE_DBTN2_state_5),
	.B0(n_355),
	.Y(n_88));
   TLATNXL \LED_WE_reg[0]  (.D(FE_OCPN16_n_172),
	.GN(n_96),
	.Q(LED_WE[0]),
	.QN(UNCONNECTED4));
   OAI21X1 g10763__1705 (.A0(n_422),
	.A1(FE_OCPN13_FE_DBTN1_state_3),
	.B0(n_429),
	.Y(n_87));
   CLKINVX2 g10768 (.A(n_400),
	.Y(n_84));
   NAND2X2 g10788__5477 (.A(n_409),
	.B(n_259),
	.Y(n_60));
   NOR2X1 g10798__6260 (.A(count[3]),
	.B(n_45),
	.Y(n_56));
   CLKINVX2 g10791 (.A(n_79),
	.Y(n_74));
   CLKINVX2 g10810 (.A(FE_OCPN4_n_259),
	.Y(n_71));
   INVXL g10804 (.A(n_409),
	.Y(n_72));
   INVXL g10817 (.A(n_442),
	.Y(n_45));
   AOI21XL g10823__2802 (.A0(count[0]),
	.A1(count[1]),
	.B0(n_318),
	.Y(n_43));
   NAND2X4 g10795__7098 (.A(n_7),
	.B(n_318),
	.Y(n_79));
   NOR2X2 g10827__6260 (.A(state[1]),
	.B(state[4]),
	.Y(n_14));
   NOR2X2 g10830__5526 (.A(count[2]),
	.B(count[3]),
	.Y(n_7));
   NOR2X4 g10831__1617 (.A(state[3]),
	.B(state[0]),
	.Y(n_37));
   INVXL g10860 (.A(rst),
	.Y(n_101));
   CLKINVX3 g10847 (.A(state[2]),
	.Y(n_15));
   CLKINVX4 g10848 (.A(state[4]),
	.Y(n_28));
   DFFSHQX4 \state_reg[0]  (.CK(clk),
	.D(n_404),
	.Q(state[0]),
	.SN(n_101));
   NOR2X6 g10834__10889 (.A(state[4]),
	.B(state[2]),
	.Y(n_119));
   CLKINVX1 g181 (.A(n_229),
	.Y(n_172));
   CLKAND2X2 g45 (.A(n_119),
	.B(n_180),
	.Y(n_181));
   NOR2X4 g46 (.A(state[1]),
	.B(state[5]),
	.Y(n_180));
   NAND2X2 g60 (.A(n_373),
	.B(n_289),
	.Y(n_187));
   NOR2X2 g91 (.A(n_192),
	.B(n_60),
	.Y(n_193));
   NAND2X2 g95 (.A(n_394),
	.B(n_397),
	.Y(n_192));
   INVXL g97 (.A(n_397),
	.Y(n_194));
   NOR2XL g94 (.A(FE_OCPN11_n_71),
	.B(FE_OCPN9_n_194),
	.Y(n_197));
   AOI22X2 g10929 (.A0(n_194),
	.A1(n_79),
	.B0(n_71),
	.B1(n_207),
	.Y(n_209));
   NOR2X4 g10794__10931 (.A(n_205),
	.B(n_206),
	.Y(n_207));
   NAND2X2 g10840__10932 (.A(count[2]),
	.B(count[3]),
	.Y(n_205));
   CLKINVX2 g10933 (.A(n_318),
	.Y(n_206));
   CLKINVX2 g10936 (.A(n_207),
	.Y(n_212));
   NOR2X1 g10937 (.A(n_399),
	.B(n_212),
	.Y(n_215));
   AOI21X1 g63 (.A0(n_222),
	.A1(n_422),
	.B0(n_223),
	.Y(n_224));
   NOR2XL g66 (.A(count[2]),
	.B(n_221),
	.Y(n_222));
   AND2X1 g65 (.A(count[2]),
	.B(n_221),
	.Y(n_223));
   NAND2X4 g41 (.A(FE_OCPN6_n_393),
	.B(n_181),
	.Y(n_229));
   NAND2X4 g268 (.A(state[2]),
	.B(FE_DBTN0_state_1),
	.Y(n_269));
   NAND2X4 g265 (.A(FE_DBTN1_state_3),
	.B(FE_DBTN2_state_5),
	.Y(n_270));
   AND2X1 g2 (.A(n_119),
	.B(n_37),
	.Y(n_289));
   NAND2X1 g10832__10960 (.A(count[0]),
	.B(n_304),
	.Y(n_221));
   CLKAND2X6 g10968 (.A(n_304),
	.B(n_317),
	.Y(n_318));
   NAND2X2 g10838__10998 (.A(state[4]),
	.B(n_15),
	.Y(n_348));
   NOR2XL g11001 (.A(FE_OCPN7_n_419),
	.B(FE_OCPN16_n_172),
	.Y(n_354));
   NAND2X2 g21 (.A(n_365),
	.B(n_364),
	.Y(n_366));
   NOR2X2 g11008 (.A(state[5]),
	.B(state[0]),
	.Y(n_364));
   NOR2X2 g22 (.A(state[3]),
	.B(state[1]),
	.Y(n_365));
   CLKINVX2 g19 (.A(count[0]),
	.Y(n_317));
   OR2X1 g11009 (.A(state[5]),
	.B(FE_DBTN0_state_1),
	.Y(n_368));
   NOR2BXL g11010 (.AN(count[3]),
	.B(n_442),
	.Y(n_369));
   OAI2BB1X1 g11014 (.A0N(FE_DBTN0_state_1),
	.A1N(state[5]),
	.B0(n_368),
	.Y(n_373));
   NAND3X2 g26 (.A(n_119),
	.B(n_180),
	.C(n_393),
	.Y(n_394));
   NOR2X2 g27 (.A(state[0]),
	.B(FE_DBTN1_state_3),
	.Y(n_393));
   NOR2X2 g35 (.A(state[5]),
	.B(FE_DBTN0_state_1),
	.Y(n_396));
   OAI22X1 g11017 (.A0(n_43),
	.A1(n_400),
	.B0(n_422),
	.B1(count[1]),
	.Y(n_401));
   NAND2X2 g11018 (.A(n_187),
	.B(n_423),
	.Y(n_399));
   OAI21X1 g10760__11019 (.A0(FE_OCPN5_n_402),
	.A1(n_422),
	.B0(n_73),
	.Y(n_404));
   NAND2X2 g11021 (.A(n_28),
	.B(n_402),
	.Y(n_405));
   NOR2X2 g10841__11022 (.A(state[3]),
	.B(n_402),
	.Y(n_406));
   NOR2X4 g11024 (.A(state[2]),
	.B(FE_DBTN2_state_5),
	.Y(n_408));
   NAND2X4 g178 (.A(n_421),
	.B(n_193),
	.Y(n_422));
   NOR2X2 g182 (.A(n_419),
	.B(n_420),
	.Y(n_421));
   NOR2X4 g188 (.A(n_348),
	.B(n_366),
	.Y(n_419));
   NOR3X4 g185 (.A(n_269),
	.B(n_270),
	.C(n_405),
	.Y(n_420));
   NOR2X1 g11029 (.A(n_419),
	.B(n_420),
	.Y(n_423));
   AOI22X1 g183 (.A0(n_79),
	.A1(FE_OCPN15_n_419),
	.B0(n_172),
	.B1(n_207),
	.Y(n_426));
   MXI2X1 g180 (.A(n_420),
	.B(n_194),
	.S0(n_74),
	.Y(n_428));
   AOI22X1 g179 (.A0(n_74),
	.A1(n_420),
	.B0(n_212),
	.B1(n_172),
	.Y(n_429));
   NOR2BX1 g11033 (.AN(count[2]),
	.B(n_221),
	.Y(n_442));
endmodule

